### ISSUE TITLE
Get error message after invoke-psake

### ISSUE THREAD

**Issue by provegard** [psake/psake#119]
If psake encounters an error, `$psake.build_success` will be `False`, so I have this in my script:

```
invoke-psake ...
if ($psake.build_success -eq $FALSE) {

}
```

In the if statement, I want to output a TeamCity error message. Question is, how do I get the error message?

In psake.psm1, there is a catch block that builds an `$error_message` variable, but it doesn't seem to be exposed.

**Comment by sideproject** [comment]
I didn't realize how old this issue was.  I have attached pull request #259 which I believe adds the requested feature.  It works for me and I am using it in production.  

Since this is such an old issue and I'm not sure anyone is still watching it I am mentioning  @devblackops  just to try and get it seen.  I apologize if this is bad form.  Please let me know if there is a better way to do this in the future.

**Comment by devblackops** [comment]
Thanks @sideproject! I'll merge your PR.
