### ISSUE TITLE
Better Import Method

### ISSUE THREAD

**Issue by flyboarder** [psake/psake#127]
Include psd1 file

This allows to extract to modules dir and import without CD into directory

current method is tedious

**Comment by vors** [comment]
Let me elaborate this issue and ramble about my personal experience and pain points.

I installed `psake` with `choco`, like all other mature modules.
Unfortunately `Invoke-PSake` didn't work, neither  `Import-Module Psake`.
The only way to call psake, which is provided by default with choco installation is `psake.bat`. 
It spawns new powershell process. Additionally psake doesn't preserve exit code. Adding another layer (new powershell process) makes automation with psake (for appveyor CI for instance) ridiculously hard.

**Comment by damianh** [comment]
@flyboarder 

Will gladly accept a PR with that.

@vors 

`choco` puts `psake.cmd` on the `$env:Path` which allows you to `psake Invoke-PSake`. It's also designed to allow you run psake from a cmd prompt(vs powershell prompt).

`Import-Module` won't search `$env:Path`, it uses `$env:PSModulePath`. Should our `chocolateyInstall.ps1` add a path to this? Not sure. cc @ferventcoder 

_Personal note: I'm not a fan of global installation of psake because there is can only be one version installed, which may change over time. I always use psake as a solution level nuget package. That is, my builds use a specific version of psake defined in version control. I don't have any problems with TC, AppVeyor etc_

**Comment by ferventcoder** [comment]
@jaykul has some good ideas with respect to how installing posh modules should put the module/version into the PSModulePath. Maybe he can elaborate on how he is doing it with his packages. I think we need to get smarter about automatically handling that stuff in the future.

**Comment by gep13** [comment]
An example of what can be done can be seen in the Pester Chocolatey Package:

https://chocolatey.org/packages/pester

@ferventcoder could this be used as a best practice guide on how to deploy PowerShell Module's with Chocolatey?

**Comment by dcjulian29** [comment]
I have my own opinion and style of installing PowerShell modules as well... :)

My personal psake chocolatey package installs psake module into the "global" system modules directory so that my build server (that runs under a different account) also has access to the module. I've thought about putting it with the source code but then you run into issues of kick-starting the package installation if the package is not already installed, potential launch failures if the package can't be downloaded and possibly issues with newer unexpected versions of the module.

You can see my install script at https://github.com/dcjulian29/choco-packages/blob/master/posh-psake/tools/chocolateyInstall.ps1 though the one for pester is definitely nice...

**Comment by devblackops** [comment]
I'm in favor of using Pester's method to copy the module to `$env:PSModulePath` (taking into account any existing versions). To me, it makes more sense that calling `choco install psake` would install the module to the same place that running `install-module psake` would.

We can then either modify the existing `psake.bat` that gets laid down in `$env:ChocolateyInstall\bin` to import the module and call `invoke-psake` with passed in args **or** modify `PATH` to include a `psake.bat` contained within the module (this is how Pester does it). I'm leaning towards keeping the existing `psake.bat` in `$env:ChocolateyInstall\bin`. We then don't need to much with `PATH`.

Thoughts @rkeithhill @gep13?

**Comment by rkeithhill** [comment]
I'm probably not a great person to ask on this one.  I think if you're on PS 5 and higher you should use `Install-Module` to install PowerShell modules.  For v3 and v4, it makes a bit more sense to use Chocolatey (even though you can install PowerShellGet Preview on those versions of PowerShell).

BTW PowerShellGet puts a `PSGetModuleInfo.xml` in the directory when it installs.  This is necessary for the `Update-Module` command to work.

**Comment by Jaykul** [comment]
Perhaps the right thing to do is definitely to install it in roughly the same way that would happen with Install-Module, (without the -Scope parameter). But that requires detecting the PowerShell version and installing to a versioned sub-folder for 5.x or removing any previous versions for 4.x and lower.  In fact, as Keith points out, it might actually overwrite versions _actually_ installed via Install-Module, breaking Update-Module 😖 

One alternative would be to create a Chocolatey-specific PowerShell module folder, and modify PSModulePath to add, say, C:\Chocolatey\Modules and install it in there ...

**Comment by ferventcoder** [comment]
Except not C:\Chocolatey.

Perhaps `$env:ChocolateyInstall\PowerShell\Modules` and maybe have Chocolatey handle this automatically? I'm thinking convention-based structure. Is there a specific structure for PowerShell NuGet modules? I have not actually looked.

We've been thinking of handling PowerShell module imports more natively and we hear from folks who would like to see PowerShell module installs at machine level, not per user.

**Comment by Jaykul** [comment]
I meant `C:\ProgramData\Chocolatey`, but obviously `$Env:ChocolateyInstall` would be better.

PowerShell nuget packages are extremely simple, it's just that PowerShell 5+ now supports installing them as `Modules\<ModuleName>\<ModuleVersion>\<ModuleName>.psd1`

**Comment by rkeithhill** [comment]
There's a minor complication with PowerShell Core and Windows PowerShell installing modules into different locations e.g. `C:\Program Files\PowerShell\Modules` vs `C:\Program Files\WindowsPowerShell\Modules`.  

By default, the two different version of PowerShell can't see modules installed by the other.  Although there is a PowerShell module this is supposed to allow PS Core to see/import Windows PowerShell modules.
