### ISSUE TITLE
psake needs a new lead maintainer

### ISSUE THREAD

**Issue by damianh** [psake/psake#130]
As I [mentioned nearly a year ago](https://groups.google.com/d/msg/psake-users/VY_Fw_coJEA/6zd9KEM_E0QJ):

> At this point, I am only interested in helping to keep psake ticking over; that is, fixing show stopping bugs (i.e. new .net framework & paths etc). I am not interested in becoming any sort of visionary, nor lead it to bigger and better things beyond the awesomeness that it already is now. As such I won't be dealing with any PRs that add or change functionality unless, again, it is a show stopper.

Since then, I have done a few releases to do just that, keep things ticking over. But this isn't enough. This is a popular package, relatively high-profile and I (we) are doing the community a disservice by less-than-half committing to it. I'm not even particularly good at powershell!

Since my google group post, .NET has became open source, recently including the important part from a powershell perspective - CoreClr. I am predicting, with a very high degree of confidence :wink: , that an open-source and x-plat powershell is en-route. As .NET becomes x-plat I can envisage psake having an important role to continue to build today's projects in an x-plat future.

**Who would like to take this over?**

**Comment by damianh** [comment]
@JamesKovacs If you happen to read this **please** make some sort of statement regarding your commitment to this project. I understand you have been offline for some time now (for reasons I don't know anything about) but perhaps it's time to set this project free.

I'd like to call out the other 'core team' members: @jmatos , @smbecker, @lanwin, @whut, @benguenter   - how do you want continue your relationship with this project?

**Comment by damianh** [comment]
@nightroman You have a very interesting alternative to psake with [Invoke-Build](https://github.com/nightroman/Invoke-Build). It's not as popular as psake because... getting traction is hard ;)

Instead of having two competing powershell build tools (not to mention all the other non-powershell ones out there), should Invoke-Build and psake join forces? Would you be interested in taking ownership here (assuming @JamesKovacs relinquishes it), make Invoke-Build obsolete and transfer the good stuff to psake? We could of course go the other way around, but transferring the community would be a lot harder.

Thoughts?

**Comment by nightroman** [comment]
@damianh,
Thank you for the call and your very reasonable thoughts.

The decision to develop Invoke-Build was not due to "not invented here" and definitely not for competition. At first I have been using psake a lot. It is an amazing tool, **great** job, the team! But psake was not designed to work in all my scenarios, quite tricky at times, including custom hosts. And psake was not easy to adjust, I saw this because I knew it and PowerShell very well.

So Invoke-Build was born and developed. It borrowed the best parts of psake, avoided some known issues, added new features. I would be very happy if the good stuff migrates from Invoke-Build to psake. I mentioned this already in various web discussions. Unfortunately I cannot take an active part in the psake project. I am committed to Invoke-Build and other things. I honestly wish psake all the best and want to help when possible. I will continue to submit issues, suggestions, thoughts, etc., as I did before. 

I am going to support Invoke-Build in the foreseen future. There is not much going on there now because the tool just perfectly fits all my needs. And the audience is not very large so that existing users are presumably happy, too. New users are welcome with their ideas, complains and suggestions.

**Comment by damianh** [comment]
@nightroman Thanks for the response, and very best of luck with it. :)

**Comment by AnneTheAgile** [comment]
Wow, as a relatively new Powershell user, the changes in the landscape are coming so fast!
@damianh and @nightroman , I wonder if either of you have reached out to the OneGet team? 
I am not clear how OneGet fits into the existing ecosystem of Psake and Invoke-Build.
AnneTheAgile

https://twitter.com/PSOneGet
https://github.com/OneGet/oneget
We have an online monthly meeting at the beginning of each month on Tuesday from 10am - 11am (PST).  //but none in November, at least not listed

**Comment by dlwyatt** [comment]
@damianh : I'd be happy to start working on the Psake project.  I'm not sure if I'll be able to commit enough time to be _lead_ maintainer; that will depend on how fast the issues / PRs / etc come in.  But I can certainly take a look at the existing backlog, and start clearing things out.

**Comment by gep13** [comment]
@dlwyatt it would be great to have you on board, with whatever help you can offer.  Like @damianh I have been helping out where I can with the psake project, pushing out releases when PR's come in, and also helping with the psake-contrib project.  I will get you added to the psake organisation so that you have access to the repositories.  Do you also have a BitBucket account?  I have set up some information that can be shared through a private repository there.

**Comment by dlwyatt** [comment]
@gep13 : I just set up a BitBucket account, dlwyatt.

**Comment by gep13** [comment]
I am going to close this one out.  For now, I think the combination of @dlwyatt and myself looking after psake is keeping the project ticking over.

**Comment by damianh** [comment]
+1
