### ISSUE TITLE
Run task multiple times

### ISSUE THREAD

**Issue by LSTANCZYK** [psake/psake#136]
I would like to run a task multiple times how can that be achieved?

**Example story:**
**Given** I have defined tasks: `Main`, `Compile` and `ReleaseOutput`
**And** Release Output task copies binaries to a folder defined in my $env:ReleasePath
**When** my main task looks like this: 

```
   Task Main {
      Invoke-Task Compile
     $env:ReleasePath = c:\path1
     Invoke-Task ReleaseOutput
     $env:ReleasePath = c:\path2
     Invoke-Task ReleaseOutput
   }
```

**Then** the second invocation of `ReleaseOutput` task should execute the task 
**And Not** skip it like it currently does.

**Comment by gep13** [comment]
@LSTANCZYK rather than run the task multiple times, can you not simply have that task enumerate a collection of paths, which you create earlier in your build script?

**Comment by iLuffy** [comment]
@gep13  I have the same request, there are some similar tasks which have the same dependent task, and we need the dependent task need to run every time, is it possible to support this?

Thank you.

**Comment by sweeneyrobb** [comment]
@iluffy, Could you not just do two Invoke-PSake commands, specifying the -taskList argument.

**Comment by iLuffy** [comment]
@sweeneyrobb 

This is the workaround, but I think it would be great if this feature is supported with depends keyword.

Thank you.

**Comment by sweeneyrobb** [comment]
@iLuffy looking at the Invoke-Task function. It seems as if there is an attempt to protect against recursion or escape any duplicate execution of a task. i'm not necessarily sure

@gep13  maybe a nifty feature would be to generate a dependency tree/graph for a particular execution and rather than execute the task graph immediately. the system can evaluate the tree for specific scenarios (recursion/circular dependencies, valid task configuration, etc). Then move the task execute task into a generation of a tree and invoking a task tree. this way you could take out the duplicate task execution, allowing users to explicitly add multiple "dependson".

I think this could do a lot for the system from a configuration validation. Maybe even add a `Test-PSake` commandlet that would validate an would-be execution without actually running the Action code block. You'd like immediately if something small is wrong in the script.

Just food for thought.

**Comment by iLuffy** [comment]
@sweeneyrobb  yeah, you are right, there is a collection to store the finished task.

@gep13  Any thought of this feature?

**Comment by gep13** [comment]
@sweeneyrobb @iLuffy I wasn't involved at the start of this project, and as a result, I don't know the history of what was and wasn't considered.  I do know that the dependency graph is executed in such a way that if multiple tasks take a dependency on the same thing, that this task will only be executed once, and this is by design, similar to a number of other build engines.  I would be hesitant to make fundamental changes in this area, as there is a risk that existing build scripts will cease to function in the way that they currently do.

**Comment by iLuffy** [comment]
@gep13 Thank you for your explanation, I understood this is by design, and I will use the workaround for this feature:)

**Comment by theunrepentantgeek** [comment]
What I do in this situation is to move the functionality into a PowerShell function, and then create a separate task for each different need:

``` PowerShell
Task Main -Depends Release.Path1, Release.Path2

Task Release.Path1 {
    Release-Output c:\path1
}

Task Release.Path2 {
    Release-Output c:\path2
}

function Release-Output( $path) { 
  # ... elided ...
}
```

The fact that a given dependency only executes once is indeed by design - and is something `PSake` shares in common with other similar tools, including `make`, `nmake`, `Fake`, `Ant`, `NAnt`, `Bake`, and `Rake`.
