### ISSUE TITLE
Overwriting $module variable in task file throws error in 4.6 (works in 4.5)

### ISSUE THREAD

**Issue by RaYell** [psake/psake#162]
I have a construct like this in my `default.ps1`

```
'MyModule1', 'MyModule2' | % {
    $moduleName = $_
    $module = Get-InstalledModule | ? Name -EQ $moduleName
    $latestVersion = (Find-Module -Name $moduleName).Version
    If (-Not $module) {
        Install-Module -Name $moduleName
    } ElseIf ($module.Version -ne $latestVersion) {
        Install-Module -Name $moduleName -Force
    }
    Import-Module -Name $moduleName
}
```

When I run my tasks with psake 4.6 I get the following error:

```
At D:\MyProject\packages\psake.4.6.0\tools\psake.psm1:392 char:15 +             . $module $init
ialization +               ~~~~~~~ [<<==>>] Exception: The term '@{Name=MyModule2; Version=1.2.3;
Description=Module 2 desc; Author=MyCompany; CompanyName=MyCompany; Copyright=; 
PublishedDate=03/16/2016 10:33:21; LicenseUri=; ProjectUri=; IconUri=; Tags=System.Object[]; 
Includes=System.Collections.Hashtable; PowerShellGetFormatVersion=; ReleaseNotes=;
Dependencies=System.Object[]; RepositorySourceLocation=https://my.company.com/nuget/; 
Repository=MyCompanyPSGallery; PackageManagementProvider=NuGet}' 
is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
```

The problem is with `$module` variable that is overwritten in a loop. Up to 4.5 this wasn't a problem but doesn't work with 4.6. Renaming the variable to `$module1` or something else fixes the problem. Perhaps there should be a list of psake-reserved variables somewhere so that we could avoid those sort of problems.

**Comment by dlwyatt** [comment]
That's a danger of how Psake currently works; just about any variable name conflict between something psake's code uses internally and a user's test code will cause problems, and it's the reason I opened issue #145.  However, fixing this problem is a big undertaking (with just about guaranteed breaking changes as well), and I haven't started on it yet.

I suppose as an interim measure, we could do something like rename any variable that psake uses internally (and isn't intended to be exposed to the user, such as function parameters on `Invoke-Psake` and the `$psake` variable) to have a prefix, something like `$__module`
