### ISSUE TITLE
Psake always throws an exception when calling git.exe and trying to clone

### ISSUE THREAD

**Issue by tfierens** [psake/psake#174]
Whenever I call git.exe using psake:

        Exec {
            &('c:\program files\git\bin\git.exe') clone git@bitbucket.org:myusername/work.git "C:\Work"
        }

It throws an error:

Error: 01/05/2016 03:20:53: At C:\temp\buildapp\psake.psm1:156 char:17 + throw ("Exec: " + $errorMessage)  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] 

Exception: Exec: Error executing command &('c:\program files\git\bin\git.exe')  clone git@bitbucket.org:myusername/work.git "C:\Work"

2 strange things:

1. It does clone the repository correctly.
2. I'd swear I got it to work a few days ago and concentrate more on the 'Pull' command as I could get it to work either!

Is this a bug with psake or git or am I doing something wrong?

Thanks.

**Comment by dlwyatt** [comment]
Is this happening from the powershell.exe console, from the ISE, or both?  The ISE treats any console application that writes to the `stderr` stream as an exception, but powershell.exe does not.  (This is because powershell.exe _is_ a win32 console application, and can just let that subsystem handle interaction with other console apps.  The ISE has its own code to pretend to be a console when it's really a WinForms app, and the behavior is different.  I believe Microsoft intends to fix this soon.)

Anyhow, git.exe writes to stderr all over the place, which is why I always keep a separate console open when I want to run git commands (so I don't have to stare at the red text all the time.)

**Comment by tfierens** [comment]
@dlwyatt You were bang on, so thanks for that! I only wished I had posted that immediately as I wasted a huge amount of time trying to figure out what was wrong. Since I'm running both clone and pull from Powershell rather than ISE, both scripts work as expected! Still can't believe this! Many thanks once again.
