### ISSUE TITLE
PSake does not seem to work on PS Core on MacOSX

### ISSUE THREAD

**Issue by dbroeglin** [psake/psake#197]
On MacOSX (PS core) psake fails because it does not find a registry or a .Net installation.
The assertion psake.psm1 fails when it tries to look for frameworks.

Steps to reproduce:

With the following `default.ps1` file:
```
task foo {
        echo "Hello World!"
}
````

When invoking `Invoke-psake` :
```
psake version 4.6.0
Copyright (c) 2010-2014 James Kovacs & Contributors

Error: 11/10/2016 22:24:43:
At /Users/dom/.local/share/powershell/Modules/psake/4.6.0/psake.psm1:193 char:9 +         throw ("Assert: " + $failureMessage) +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Assert: No .NET Framework installation directory found at \Microsoft.NET\Framework64\v4.0.30319\.
```

**Comment by gep13** [comment]
@dbroeglin to the best of my knowledge, I don't think any work has been done to support PS Core, so it isn't a surprise that it doesn't work.

If you are in a position to submit a PR to help with this then we would welcome it.

@dlwyatt is this something you have looked at?

**Comment by dbroeglin** [comment]
I will try to look into it, I like psake a lot and would very much like to see it work on my Mac where I do most of my work ;-)

Crude workaround: comment both occurrences of `ConfigureBuildEnvironment`. Could you give me a bit of guidance about why psake needs the .Net framework and under which circumstances it would be safe to not have it ? I try to look into the code and submit a PR.

**Comment by larssb** [comment]
Any news on this?

**Comment by rkeithhill** [comment]
In theory PR #198 fixed it. Care to download the repo and give it a go and see if it works?  We need to get more folks using/testing on Linux/macOS so we can make Windows specific dependencies load conditionally upon the platform.

**Comment by michaeltlombardi** [comment]
```powershell
git clone https://github.com/psake/psake.git
Set-Content ./default.ps1 "task default -depends foo`ntask foo { Write-Host 'Hello World' }"
Import-Module .\psake\psake.psd1
Invoke-Psake
```

^ That worked without errors. However, what's in master is 46 commits ahead of the latest available on the gallery, `4.6.0`.

**Comment by rkeithhill** [comment]
Yup, we desperately need someone to release a new version.  @PowerSchill do you know the release process for psake?  Looks like @dlwyatt and/or @gep13 was the last to push a new version to PSGallery.

**Comment by larssb** [comment]
@michaeltlombardi thank you for testing it. @rkeithhill thank you for responding. Looks like we are progressing again :-)

Thank you all.

**Comment by gep13** [comment]
@rkeithhill sorry, can't help with pushing to the PSGallery, as that wasn't me.  Think it must have been @dlwyatt.

Going forward, as suggested to @daviwil about a few other things, ideally this operation, like others, should be done by a common psake user/account, so that we are not limited to a single person to do the work.  The details of this common user/account, can then be shared within the team.

**Comment by rkeithhill** [comment]
Well the problem with that is the PSGallery requires an api key to allow publishing.  You do not want that api key checked in, although I guess it could be supplied as a secret in a Travis or AppVeyor build.

**Comment by gep13** [comment]
@rkeithhill there is a shared keepass database, committed into a private git repository that is shared between the project maintainers.  Quite a crude way of sharing the sensitive information, but it gets the job done.  If you wanted to automate that process as part of your CI build, then definitely, this could be added to Travis and AppVeyor in a secure way.

**Comment by devblackops** [comment]
I'd be wary of putting the API key in AppVeyor as a secret. Unless extra steps are taken, a malicious pull request can include code that is executed during the build process to expose the environment variables in AppVeyor.

**Comment by rkeithhill** [comment]
@dlwyatt Hey Dave, any chance you could push an updated version of psake to the PSGallery?  I think @PowerSchill is willing to take over, maybe add him as another owner of pake on the gallery?

**Comment by devblackops** [comment]
> That worked without errors. However, what's in master is 46 commits ahead of the latest available on the gallery.

Sounds like a [changelog](http://keepachangelog.com/) needs to be setup 😏
 I have access to push to PSGallery now and can do so but would like to compile a list of changes since `v4.6.0`. I'm assuming this will follow [semantec versioning](http://semver.org/) so need to determine if will be a `v4.7.0` or `v4.6.1` release. With that many commits since the last release, I'm guessing `v4.7.0`.

**Comment by rkeithhill** [comment]
Thanks!  It looks like the bulk of the early commits were doc related.  The externally visible commits pretty much are related to fixing psake to run cross-platform on PowerShell Core.  There are quite a few infrastructure commits made by @PowerSchill to get build/test going on PS Core.  There is one commit I'd really like to get before we release an update and that is support for VS 2017 (when running on Windows).  This PR #219 is close but we can't add a dependency on VSSetup in the PSD1 file because this dependency applies only to Windows.  I've suggested how the PR can be fixed to check for/load the module at runtime.

**Comment by devblackops** [comment]
@rkeithhill Sounds good.

I've added the changelog [here](https://github.com/psake/psake/blob/master/CHANGELOG.md).

I'd also like to square away the AppVeyor and Travis CI builds and get Pester working with those. Hopefully can get to more frequent releases soon.

**Comment by rkeithhill** [comment]
If we can get the VS 2017 support in, I say we call it `v4.7.0`.  Even if it is just cross-platform PowerShell Core in this release, that is probably enough to call it `v4.7.0`.

**Comment by devblackops** [comment]
`v4.7.0` released to PSGallery, Chocolatey (awaiting review), and nuget.org.

https://www.powershellgallery.com/packages/psake/4.7.0
