### ISSUE TITLE
Changed folder structure

### ISSUE THREAD

**Issue by tapmantwo** [psake/psake#233]
Hi - not a major gripe, but the latest release has moved the actual scripts and modules from \tools to \tools\psake.

Given instructions say to 'change directory to where the psake.pm1 file is', that's a bit of shame.  We've had to update our build to the new location.

Was there a good reason for this change?

**Comment by devblackops** [comment]
Hi @tapmantwo. This was a side effect of moving the actual PS module under the `src` folder instead of having everything at the root of the project. The build process followed suit. See https://github.com/psake/psake/issues/226. Perhaps `psake.ps1` and `psake.cmd` should be moved back to `\tools` instead of `\tools\psake` during the nuget build process.

Are one of those two files what you're actually calling instead of the module directly?

Sorry for the headache

-Brandon

**Comment by tapmantwo** [comment]
Hi Brandon - I don't think you necessarily have to revert it if you feel it was a necessary change.  I just wanted to flag it up as a 'breaking' change so to speak.

We do run the ps1 file directly - partly because of ignorance, but the readme does also say `CD into the directory where you extracted the project (where the psake.psm1 file is)`.  Is it best practise to run the init.ps1 from the .\tools folder instead, and use the module instead?

**Comment by devblackops** [comment]
I think the readme should be updated. Since psake is in the [PowerShell Gallery](https://www.powershellgallery.com/packages/psake/4.7.0) now, the preferred way to install it is via `Install-Module` and not to manually download the artifact zip. You can then just use `invoke-psake` directly and not have to use the `psake.ps1/psake.cmd` shims.

**Comment by jozefizso** [comment]
Our build scripts have issues with this change too.

Changing folder structure is a breaking change, yet it happened in a minor release.
