### ISSUE TITLE
psake 4.7 does not work with Visual Studio 2017

### ISSUE THREAD

**Issue by jozefizso** [psake/psake#241]
## Expected Behavior
Include psake 4.7.0 using nuget in the project. Use `Framework "4.6"` in psake build script. Psake should automatically detect Visual Studio 2017 and use correct toolset.

## Current Behavior
Psake will use Visual Studio 2015 and older toolset which caused the build to fail.

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 build tools.
 Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
```

## Possible Solution
Psake must contain logic for detecting Visual Studio 2017. This detection must be included in the psake so we don't have to install another PowerShell scripts and modules on machines.
This should work out of the box.

## Steps to Reproduce (for bugs)
1. Reference psake 4.7.0 using nuget
2. Create Visual C++ project using Visual Studio 2017 and target toolset 141.
3. Try to build project using psake.

## Context
We use psake to build our solutions and projects. We reference a single psake package using nuget and this is a self contained set of scripts which should be able to compile VS2017 based projects.

It's not feasible to install and manage PowerShell modules on each developer and build machines just becasue build scripts cannot properly detect Visual Studio and are not extensible to be self-contained.

## Your Environment
* Module version used: 4.7.0
* Operating System and PowerShell version: Windows 10, PowerShell 5

**Comment by mderriey** [comment]
I believe psake has VS 2017/MSBuild 15 support, but the detection relies on a separate PowerShell module called [VSSetup](https://github.com/microsoft/vssetup.powershell) as you can see [here in the code](https://github.com/psake/psake/blob/4784d5ee970201d60280395aa7a9cb5528b7dfdd/src/private/ConfigureBuildEnvironment.ps1#L94-L99).

When running your psake build, can you, by any chance, see the following warning message?

```
Warning: Cannot find build tools version 15.0 without the module VSSetup. You can install this module with the command: Install-Module VSSetup -Scope CurrentUser
```

If so, you could try to run `Install-Module VSSetup -Scope CurrentUser` at the beginning of your psake script so that the detection works as expected.

**Comment by eeevans** [comment]
I still can't get this to work...not sure what the issue is.  
I get:  
Exception: The following error occurred while loading the extended type data file: Error in TypeData "Microsoft.VisualStudio.Setup.Instance": Type "Microsoft.VisualStudio.Setup.PowerShell.InstanceAdapter" should be a PSPropertyAdapter.
Modules:
1.1.7.2              PackageManagement                   PSGallery            PackageManagement (a.k.a. One... 1.6.5                PowerShellGet                       PSGallery            PowerShell module with comman... 
4.7.0                psake                               PSGallery            psake is a build automation t... 
2.0.1.32208          VSSetup                             PSGallery            Visual Studio Setup PowerShel..
