### ISSUE TITLE
Psake (4.4.1) task definition requires curly braces to be on same line as task name

### ISSUE THREAD

**Issue by raghav710** [psake/psake#251]
## Expected Behavior
A task should be executable irrespective of whether the curly braces are on the same line or the next

## Current Behavior
When I put the open curly brace `{` on the next line of the task name while defining a task, the contents of the task are printed instead of it being executed

## Steps to Reproduce (for bugs)
**Code 1:**
    task default -depends test
    task test {
        Write-Host "hi"
    }

Output is 
    Executing test
    hi

**Code 2:**
    task default -depends test
    task test 
    {
        Write-Host "hi"
    }

Output is:
       Write-Host "hi"

## Your Environment
* Module version used: 4.4.1
* Operating System and PowerShell version: Windows 7, Powershell v5.0.10586.117

**Comment by devblackops** [comment]
Hi @raghav710 

This is because the code you're supplying to the task is actually a `scriptblock` parameter. This is a bit different than statements like `function`, `if/else`, `while`, etc where you can put the brace `{` at the end of the line or on a new line.

`task` is actually just a function with a bunch of positional parameters. When you type:

```powershell
task test {
    Write-Host "hi"
}
```

You're actually running `task -name 'test' -action { write-host "hi" }`

This requires the opening brace `{` to be on the same line so PowerShell interprets it as a value to the parameter.

**Comment by raghav710** [comment]
Thanks for the detailed reply. This was quite useful. Please feel free to close the issue

**Comment by devblackops** [comment]
No problem!
